/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teste.pkg2;

import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lucia
 */
public class InterfaceGraficaServer extends javax.swing.JFrame {
    
    private Server server;
    
    /**
     * Creates new form InterfaceGraficaServer
     */
   
    public InterfaceGraficaServer(int port) throws IOException {
        System.out.println("port = " + port);
        server = new Server(port);
        server.start();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mensagemTextField = new javax.swing.JTextField();
        criptografiaTextField = new javax.swing.JTextField();
        algoritmoTextField = new javax.swing.JTextField();
        enviarButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        binarioTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        jLabel1.setText("msg");

        jLabel2.setText("cript");

        jLabel3.setText("alg");

        enviarButton.setText("enviar");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("bin");

        binarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binarioTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(criptografiaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(algoritmoTextField)
                            .addComponent(mensagemTextField)
                            .addComponent(binarioTextField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(mensagemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(criptografiaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(binarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(algoritmoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(enviarButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private ArrayList<Boolean> strToBinary(String s) throws UnsupportedEncodingException
    {
        //retorna o valor da string em ascII extendido 
        int n = s.length();
        ArrayList<Boolean> palavra = new ArrayList<>();
        for (int i = 0; i < n; i++)
        {
            int val;
            ArrayList<Boolean> letra = new ArrayList<>();
            
            val = (int) s.charAt(i);
            while (val > 0){
                if (val % 2 == 1){
                    letra.add(true);
                }
                else
                    letra.add(false);
                val /= 2;
            }
            while(letra.size() < 8)     //garante que a letra tenha 8 bits
            {
                letra.add(false);
            }
            for(int j=7; j>=0; j--)      //adiciona a letra a palavra
            {
                palavra.add(letra.get(j));
            }
        }
        return palavra;
    }
    
    private String arrayToStr(ArrayList<Boolean> palavra)
    {
        String output = "";
        for(int i=0; i<palavra.size();i++)
        {
            if(palavra.get(i)){
                output += '1';
            }
            else{
                output += '0';
            }
        }
        return output;
    }
    
    private ArrayList<Integer> binToAlg(ArrayList<Boolean> bin){
        
        //| next | posi | nega |
        //|  00  |  +1  |  -1  |
        //|  01  |  +3  |  -3  |
        //|  10  |  -1  |  +1  |
        //|  11  |  -3  |  +3  |
        ArrayList<Integer> alg = new ArrayList<>();
        boolean sigAnterio = true; //true é positivo false é negativo
        
        for(int i=0; i<bin.size(); i+=2)
        {
            if(bin.get(i+1) == false && bin.get(i) == false){       //00
                if(sigAnterio){
                    alg.add(1);
                    sigAnterio = true;
                }
                else{
                    alg.add(-1);
                    sigAnterio = false;
                }
            }
            else if(bin.get(i+1) == false && bin.get(i) == true){   //01
                if(sigAnterio){
                    alg.add(3);
                    sigAnterio = true;
                }
                else{
                    alg.add(-3);
                    sigAnterio = false;
                }
            }
            else if(bin.get(i+1) == true && bin.get(i) == false){   //10
                if(sigAnterio){
                    alg.add(-1);
                    sigAnterio = false;
                }
                else{
                    alg.add(1);
                    sigAnterio = true;
                }
            }
            else if(bin.get(i+1) == true && bin.get(i) == true){    //11
                if(sigAnterio){
                    alg.add(-3);
                    sigAnterio = false;
                }
                else{
                    alg.add(3);
                    sigAnterio = true;
                }
            }
        }
        
        return alg;
    }
    
    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        try {
            // TODO add your handling code here:
            String msg = mensagemTextField.getText();
            //String criptogra = new String;
            ArrayList<Boolean> bin = strToBinary(msg);
            ArrayList<Integer> alg = binToAlg(bin);
            
            System.out.println("msg = " + msg);
            System.out.println("bin = " + arrayToStr(bin));
            System.out.println("alg = " + alg);
            
            binarioTextField.setText(arrayToStr(bin));
            algoritmoTextField.setText(alg.toString());
            
            server.sendMsg(bin);
        } catch (IOException ex) {
            //ninguem conectado
            Logger.getLogger(InterfaceGraficaServer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void binarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_binarioTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField algoritmoTextField;
    private javax.swing.JTextField binarioTextField;
    private javax.swing.JTextField criptografiaTextField;
    private javax.swing.JButton enviarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mensagemTextField;
    // End of variables declaration//GEN-END:variables
}
